apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-backend-secrets
  namespace: app
spec:
  provider: azure
  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: db-host
          key: DB_HOST
        - objectName: db-port
          key: DB_PORT
        - objectName: db-name
          key: DB_NAME
        - objectName: db-user
          key: DB_USER
        - objectName: db-password
          key: DB_PASSWORD
        - objectName: cors-origin
          key: CORS_ORIGINS
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "17b5f45e-bf78-433b-9fb6-208ab552bdd1"
    keyvaultName: "aks-key-vault-lab"
    tenantId: "2729a7ff-7be7-41e4-a330-576562aaaf8e"
    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-port
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: cors-origin
          objectType: secret